// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UtmaningEtt;

namespace UtmaningEtt.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("GamePlatform", b =>
                {
                    b.Property<int>("Gamesid")
                        .HasColumnType("int");

                    b.Property<int>("Platformsid")
                        .HasColumnType("int");

                    b.HasKey("Gamesid", "Platformsid");

                    b.HasIndex("Platformsid");

                    b.ToTable("GamePlatform");
                });

            modelBuilder.Entity("UtmaningEtt.Game", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<float>("cost")
                        .HasColumnType("real");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("platform_id")
                        .HasColumnType("int");

                    b.Property<int>("publisher_id")
                        .HasColumnType("int");

                    b.Property<int>("release_year")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("UtmaningEtt.Platform", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("is_handheld")
                        .HasColumnType("bit");

                    b.Property<int>("max_players")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("publisher_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("UtmaningEtt.Publisher", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Gameid")
                        .HasColumnType("int");

                    b.Property<string>("country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("net_worth")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("Gameid");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("GamePlatform", b =>
                {
                    b.HasOne("UtmaningEtt.Game", null)
                        .WithMany()
                        .HasForeignKey("Gamesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UtmaningEtt.Platform", null)
                        .WithMany()
                        .HasForeignKey("Platformsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UtmaningEtt.Publisher", b =>
                {
                    b.HasOne("UtmaningEtt.Game", null)
                        .WithMany("Publishers")
                        .HasForeignKey("Gameid");
                });

            modelBuilder.Entity("UtmaningEtt.Game", b =>
                {
                    b.Navigation("Publishers");
                });
#pragma warning restore 612, 618
        }
    }
}
